### ISSUE TITLE
Fatel error when interpolation in scss

### ISSUE THREAD

**Issue by ajithr** [sasstools/sass-lint#674] opened 2016-05-04 18:17 UTC
I am using latest version of sass-lint in my project. When I tried to interpolate two variables in the scss file, it throws the fatel error in the sass-lint linter.

![image](https://cloud.githubusercontent.com/assets/8641400/15024401/61298058-1252-11e6-8c6a-c711e266e5f8.png)

**Example:**

```
@mixin border($area){
  @each $pos in top, left, bottom, right {
   .#{$area}-#{$pos}-border{
      border-#{$pos}: 1px solid;
    }
  }
}
@include border(header);
```

**.#{$area}-#{$pos}-border{** this line throws the exact error.

**Comment by bgriffith** [comment] 2016-05-05 22:32
Hey @ajithr - Thanks for the report.

It appears to be a duplicate of #644 where the AST has an issue with hyphens and interpolate values.

Please follow #644, and I'll close this one.

**Closed by bgriffith** 2016-05-05 22:32 UTC
