### ISSUE TITLE
Allow rules as a plugin

### ISSUE THREAD

**Issue by gajus** [sasstools/sass-lint#432] opened 2015-11-23 12:33 UTC
There appears to be no way to have rules loaded as a plugin.

Ideally, a custom rule should be declared using `plugin-{rule-name}`:

```yml
rules:
  extends-before-mixins: 2
  extends-before-declarations: 2
  placeholder-in-extend: 2
  plugin-{rule-name}
```

`sass-lint` in turn would attempt to find a peer dependency called `sass-lint-plugin-{rule-name}`, e.g. I would like to publish rule `sass-lint-plugin-property-sort-order`.

**Comment by Snugug** [comment] 2015-11-23 12:39
Duplicate of https://github.com/sasstools/sass-lint/issues/139

On roadmap for 2.0 https://github.com/sasstools/sass-lint/issues/400

**Closed** 2015-11-23 13:06 UTC
