### ISSUE TITLE
interpolation: parsing error

### ISSUE THREAD

**Issue by ebess** [sasstools/sass-lint#453] opened 2015-12-14 09:08 UTC
Code:
```sass
@each $direction in (top right bottom left) {
    &.#{$direction} .arrow:after {
        border-#{$direction}-color: $color-inverse;
    }
}
```
Output:
```
/var/www/bbc/node_modules/gulp-sass-lint/node_modules/sass-lint/lib/groot.js:21
    throw new Error('Parsing error' + fileInfo + ': ' + e.message);
    ^

Error: Parsing error at src/styles/popover/_popover.scss: Please check validity of the block starting from line #20
    at module.exports (/var/www/bbc/node_modules/gulp-sass-lint/node_modules/sass-lint/lib/groot.js:21:11)
    at Function.sassLint.lintText (/var/www/bbc/node_modules/gulp-sass-lint/node_modules/sass-lint/index.js:36:13)
    at DestroyableTransform._transform (/var/www/bbc/node_modules/gulp-sass-lint/index.js:38:27)
    at DestroyableTransform.Transform._read (/var/www/bbc/node_modules/gulp-sass-lint/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:10)
    at DestroyableTransform.Transform._write (/var/www/bbc/node_modules/gulp-sass-lint/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:160:12)
    at doWrite (/var/www/bbc/node_modules/gulp-sass-lint/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:333:12)
    at writeOrBuffer (/var/www/bbc/node_modules/gulp-sass-lint/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:319:5)
    at DestroyableTransform.Writable.write (/var/www/bbc/node_modules/gulp-sass-lint/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:246:11)
    at write (/var/www/bbc/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/var/www/bbc/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (/var/www/bbc/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:664:5)
    at emitNone (events.js:67:13)
    at DestroyableTransform.emit (events.js:166:7)
    at emitReadable_ (/var/www/bbc/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:448:10)
    at emitReadable (/var/www/bbc/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:444:5)
    at readableAddChunk (/var/www/bbc/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:187:9)
```
Line 20 block is the ```border-#{$direction}-color: $color-inverse;``` line.

**Comment by benthemonkey** [comment] 2015-12-14 17:37
I believe this is a duplicate of #321

**Comment by DanPurdy** [comment] 2015-12-14 19:06
Closing duplicate, we'll track it all in the other issue as the AST updates..

**Closed by DanPurdy** 2015-12-14 19:06 UTC
Labels: duplicate
