### ISSUE TITLE
[sass|scss] css variable don't work

### ISSUE THREAD

**Issue by hopefuture** [sasstools/sass-lint#1098] opened 2017-07-18 11:17 UTC
When I use css variable to write style. There is a error tooltip: "Please check validity of the block starting from line "

example 

```
:root {
  --theme-color: #346789;
}
```

**Comment by eugef** [comment] 2017-07-31 11:43
Any update on supporting css variables?

**Comment by bgriffith** [comment] 2017-08-28 16:12
Going to close as this is a duplicate of https://github.com/sasstools/sass-lint/issues/877

A fix is on the way.

**Closed by bgriffith** 2017-08-28 16:12 UTC
Labels: ast, externally blocked
