### ISSUE TITLE
Keyframes parsing issue?

### ISSUE THREAD

**Issue by scottbert** [sasstools/sass-lint#642] opened 2016-04-22 16:16 UTC
Just upgraded from sass-lint 1.5.1 to 1.6.2
```scss
@keyframes liquid-tube {
  0% {    // Line 1165
    opacity: 0;
    transform: scale(1, 1);
  }

  10% {
    opacity: 1;
    transform: scale(1, 1);
  }

  50%, 100% {
    opacity: 1;
    transform: scale(1, 0);
  }
}
```
"sass-lint Error Fatal Please check validity of the block starting from line #1165". Seems like there may be a bug? Appears to be the case in 1.6.0 and 1.6.1 too.

**Comment by bgriffith** [comment] 2016-04-22 16:27
Hey @scottbert - Managed to reproduce it.

Seems to be the use of the comma and two properties `50%, 100%`.

**Comment by Kunepro** [comment] 2016-05-05 17:41
+1
Same problem, with any "n%".
The problem is in parsing that comma.
I'm temporally disabling sass-lint waiting for a fix.

**Comment by DanPurdy** [comment] 2016-05-05 17:43
It's not a sass-lint issue, it's an issue with AST we're using so fixes may not be quick..

**Comment by bgriffith** [comment] 2016-05-14 18:36
Just to update that I have fix (https://github.com/tonyganch/gonzales-pe/pull/175) for this so hopefully we'll get an update out soon.

**Comment by jessepollak** [comment] 2016-05-25 18:52
Awesome work here! Would it help if I opened a PR with the version bump for `gonzales-pe`? Cheers!

**Comment by DanPurdy** [comment] 2016-05-25 19:12
@jessepollak we've already got one thanks

**Comment by DanPurdy** [comment] 2016-06-16 12:47
This will be fixed when 1.8 is released

**Comment by arcanis** [comment] 2016-06-17 08:53
Just for information, is there an ETA for the 1.8 release ? Would you say it's a matter of days or weeks ?

**Comment by bgriffith** [comment] 2016-06-17 08:58
Days if not today.

**Comment by DanPurdy** [comment] 2016-06-17 14:07
@arcanis Sass-lint 1.8 is out now

**Closed by DanPurdy** 2016-06-17 14:07 UTC
Labels: ast, bug

**Comment by nithin123456** [comment] 2016-10-21 23:42
is this issue fixed???



    @keyframes #{pulsate}-#{$i} {
      0% {
        -webkit-transform: rotate($i) scale(1);
        -moz-transform: rotate($i) scale(1);
        -ms-transform: rotate($i) scale(1);
        -o-transform: rotate($i) scale(1);
        transform: rotate($i) scale(1);
      }
      50% {
        -webkit-transform: rotate($i) scale(1.5);
        -moz-transform: rotate($i) scale(1.5);
        -ms-transform: rotate($i) scale(1.5);
        -o-transform: rotate($i) scale(1.5);
        transform: rotate($i) scale(1.5);
      }
      100% {
        -webkit-transform: rotate($i) scale(1);
        -moz-transform: rotate($i) scale(1);
        -ms-transform: rotate($i) scale(1);
        -o-transform: rotate($i) scale(1);
        transform: rotate($i) scale(1);
      }
    }

still get the error 
Please check validity of the block starting from line #400  Fatal

Currently using https://www.npmjs.com/package/gulp-sass-lint which picks up sass-lint 1.9.1

**Comment by DanPurdy** [comment] 2016-10-22 11:23
@nithin123456 this is a different issue, the issue you're seeing is due to the interpolation in the keyframes name. If you remove the `-#{$i}` it will parse fine so there's a bug in the AST we use when parsing interpolated keyframe identifiers.

**Comment by jtarantinomastercard** [comment] 2016-12-12 21:45
@DanPurdy I seem to have a similar issue working with what appears to be a simple mixin:

mixin:
```
=keyframes($name)
  // sass-lint:disable-block indentation
  @-webkit-keyframes #{$name}
    @content
  @-moz-keyframes #{$name}
    @content
  @-ms-keyframes #{$name}
    @content
  @keyframes #{$name}
    @content
```

usage:
```
+keyframes(blink)
  0%
    opacity: 0
    display: block
  30%
    opacity: 1
  70%
    opacity: 1
  100%
    opacity: 0
    display: none
```

Is this also caused by the AST issue you mentioned in https://github.com/sasstools/sass-lint/issues/642#issuecomment-255522783 ? Any ideas how to get around it?

**Comment by rardoz** [comment] 2017-05-22 19:54
This is still an issue on 1.10.2
