### ISSUE TITLE
no-color-literals fails on variable names in maps

### ISSUE THREAD

**Issue by vsiao** [sasstools/sass-lint#651] opened 2016-04-27 01:52 UTC
```scss
$palette-teal: (
  core: $teal
);
```

**Expected**: no failure
**Actual**: `2:10 warning  Color literals such as 'teal' should not be used as map identifiers`

**Comment by DanPurdy** [comment] 2016-04-27 08:31
Duplicate of #538 and will be fixed in #647

**Closed by DanPurdy** 2016-04-27 08:31 UTC
