### ISSUE TITLE
Sass lint stop working on concatenated strings

### ISSUE THREAD

**Issue by soloproyectos** [sasstools/sass-lint#745] opened 2016-06-19 17:16 UTC
Does not work:
```sass
.ui-contents {
  display: table-cell;
  text-align: center;
  vertical-align: middle;
  // here's the problem
  background: url($images_path + '/login_view/logo.png') no-repeat center 18%;
}
```

Mysteriously works:
```sass
.ui-contents {
  display: table-cell;
  text-align: center;
  vertical-align: middle;
  background: url($images_path + '/login_view/logo.png');
}
```

Works perfectly:
```sass
.ui-contents {
  display: table-cell;
  text-align: center;
  vertical-align: middle;
  background: url('#{$images_path}/login_view/logo.png') no-repeat center 18%;
}
```

**Additional info:**
linter-sass-lint version: 1.6.1
Atom version: 1.8.0
Sass version: Sass 3.4.22 (Selective Steve)
OS version: Xubuntu 16.04

**Comment by DanPurdy** [comment] 2016-06-20 10:29
Thanks for the report, it's an issue with the AST we use.

Also a duplicate of https://github.com/sasstools/sass-lint/issues/63

**Closed by DanPurdy** 2016-06-20 10:29 UTC
