### ISSUE TITLE
A value of `0` is not allowed. `0` must be used  border-zero

### ISSUE THREAD

**Issue by seeliang** [sasstools/sass-lint#870] opened 2016-09-13 07:05 UTC
What version of Sass Lint are you using?
Not using 

Please include any relevant parts of your configuration
  border-zero:
    - 1
    - convention: 0

What did you do? Please include the actual source code causing the issue.
  @include screen(sm-phone) {
    border: 0;
    padding: 0;
  }

What did you expect to happen?
no error 

What actually happened? Please include any error messages given to you by Sass Lint.
A value of `0` is not allowed. `0` must be used  border-zero

If you're using a IDE plugin have you tried the CLI too?
i am using gulp-sass-lint Atom and VIM, same error message

**Comment by DanPurdy** [comment] 2016-09-13 09:39
Hi there this is a duplicate of #861

**Closed by DanPurdy** 2016-09-13 09:39 UTC
