### ISSUE TITLE
Parsing error when using extrapolated variable as extend name

### ISSUE THREAD

**Issue by micahgodbolt** [sasstools/sass-lint#313] opened 2015-10-16 17:11 UTC
Getting parsing errors when I try to use an extrapolated variable in a silent extend.

```bash
Warning: Parsing error at test/fixtures/test1.scss: Please check validity of the block starting from line #3 Use --force to continue.
```

```sass
$var: 'foo';

%#{$var} {
  font-size: 18px;
}
```

**Comment by bgriffith** [comment] 2015-10-16 20:50
Hey @micahgodbolt - thanks for the issue. It's currently being caused by the parser so I've added an issue. Here's a reference https://github.com/tonyganch/gonzales-pe/issues/110

**Comment by DanPurdy** [comment] 2015-10-19 21:28
Confirmed as working in gonzales-pe 3.2.1

**Comment by danez** [comment] 2016-02-04 13:27
As far as I can see gonzales-pe >= 3.0.0 fixed the issue. When I look at the PR it seems you are preparing to upgrade to version 3.2 soon, right? Do you guys have any eta when this will be finished? Or maybe upgrade to 3.0.x before 3.2 if there are no so many breaking changes in it?

We would love to use sass-lint, but this bug keeps us from doing that.

**Comment by DanPurdy** [comment] 2016-02-04 14:07
3.0 contains as many breaking changes as 3.2.. there are still regressions in 3.2 that are going to need to be fixed before this is complete but fingers crossed! As for an eta, whenever we get the time to work on it, i'm afraid i can't be any more specific than that. 

Might be worth keeping an eye on this issue though, https://github.com/sasstools/sass-lint/issues/495

**Comment by bgriffith** [comment] 2016-04-22 08:29
@micahgodbolt The parse error has been fixed in 1.6.

**Closed by bgriffith** 2016-04-22 08:29 UTC
Labels: ast, bug, externally blocked, fixed in gonzales-3.2.6

**Comment by DanPurdy** [comment] 2016-04-22 11:28
ping @danez too ^^
